TWITTER_API_KEY_ENV = 'TWITTER_API_KEY'
TWITTER_API_SECRET_ENV = 'TWITTER_API_KEY_SECRET'
TWITTER_BEARER_TOKEN_ENV = 'TWITTER_BEARER_TOKEN'
TWITTER_ACCESS_KEY_ENV = 'TWITTER_ACCESS_KEY'
TWITTER_ACCESS_SECRET_ENV = 'TWITTER_ACCESS_KEY_SECRET'

DISCORD_BOT_TOKEN_ENV = 'DISCORD_BOT_TOKEN'