TWITTER_API_KEY_ENV = 'TWITTER_API_KEY'
TWITTER_API_SECRET_ENV = 'TWITTER_API_KEY_SECRET'
TWITTER_BEARER_TOKEN_ENV = 'TWITTER_BEARER_TOKEN'
TWITTER_ACCESS_KEY_ENV = 'TWITTER_ACCESS_KEY'
TWITTER_ACCESS_SECRET_ENV = 'TWITTER_ACCESS_KEY_SECRET'

TWITTER_TARGET_USER_ENV = 'TWITTER_TARGET_USER'

DISCORD_BOT_TOKEN_ENV = 'DISCORD_BOT_TOKEN'

HTTP_PORT_ENV = 'HTTP_PORT'
HTTP_REDIRECT_TARGET_ENV = 'HTTP_REDIRECT_TGT'